Update patch set 6
Patch Set 6: Verified-1

> Patch Set 5: Verified+1 Code-Review+1
> 
> Works for me.  Will wait for Marco to also verify it, to be sure.

=> [1] passes, however [2] leads to [2]'s error for me locally, also after cleaning all of my bazel caches up. This plugin has no test targets, but maybe [2] should still not fail that way. We may need to test this topic with another plugin that does have tests. Note that running [3] locally leads to similar errors, unsurprisingly.

[1] bazel build admin-console
[2] bazel test //...
=>
ERROR: /home/lmcmmil/git/gerrit/plugins/stable-2.14/admin-console/tools/eclipse/BUILD:1:1: file '//tools/bzl:classpath.bzl' does not contain symbol 'classpath_collector'
ERROR: /home/lmcmmil/git/gerrit/plugins/stable-2.14/admin-console/tools/eclipse/BUILD:4:1: name 'classpath_collector' is not defined
ERROR: package contains errors: tools/eclipse
ERROR: error loading package 'tools/eclipse': Package 'tools/eclipse' contains errors

[3] ./tools/eclipse/project.sh

Patch-set: 6
Reviewer: Gerrit User 1012732 <1012732@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1