Update patch set 1
Patch Set 1:

> Patch Set 1: Verified-1
> 
> Build fails not with the code but ./tools/eclipse/project.sh:
> 
> ERROR: /home/user/git/gerrit/plugins/master/admin-console/tools/eclipse/BUILD:4:1: in classpath_collector rule //tools/eclipse:main_classpath_collect:
> Traceback (most recent call last):
>         File "/home/user/git/gerrit/plugins/master/admin-console/tools/eclipse/BUILD", line 4
>                 classpath_collector(name = 'main_classpath_collect')
>         File "/home/user/.cache/bazel/_bazel_user/aebbecb4913caf0030850735ba84ceda/external/com_googlesource_gerrit_bazlets/$ools/classpath.bzl", line 5, in _classpath_collector
>                 all.append(d.java.transitive_runtime_deps)
>         File "/home/user/.cache/bazel/_bazel_user/aebbecb4913caf0030850735ba84ceda/external/com_googlesource_gerrit_bazlets/$ools/classpath.bzl", line 5, in all.append
>                 d.java.transitive_runtime_deps
> object of type 'JavaSkylarkApiProvider' has no field 'transitive_runtime_deps'

I suspect this is caused by incompatible_disallow_legacy_java_provider which was fixed in core Gerrit by [1] but has not yet been applied to bazlets.

What version of bazel are you using?  It works OK for me with 0.29.1

[1] https://gerrit-review.googlesource.com/c/gerrit/+/236272

Patch-set: 1
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>