Update patch set 4
Patch Set 4: Code-Review+1

It seems to fail with

paladox@gerrit-test:~/gerrit$ bazel build plugins/admin-console
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
INFO: From Building gerrit-server/libserver.jar (1306 source files, 41 resources):
Note: gerrit-server/src/main/java/com/google/gerrit/server/api/changes/ChangeApiImpl.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
ERROR: /home/paladox/gerrit/plugins/admin-console/BUILD:3:1: Java compilation in rule '//plugins/admin-console:admin-console__plugin' failed: Worker process sent response with exit code: 1.
plugins/admin-console/src/main/java/com/googlesource/gerrit/plugins/adminconsole/ShowAccountCommand.java:124: error: cannot find symbol
            .byAccount(account.getId())) {
            ^
  symbol:   method byAccount(Id)
  location: interface AccountExternalIdAccess
1 error
Target //plugins/admin-console:admin-console failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 67.499s, Critical Path: 52.15s

though this problem was not introduced by this commit.

It just exposes the problem now :)

I doint know how to fix that error @David Ostrovsky would you know how to fix that please?

Patch-set: 4
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=+1